version: "3"

services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    environment:
      - MYSQL_ROOT_PASSWORD=testing-password
    ports:
      - "8000"

  elasticsearch:
    image: elasticsearch:7.3.0
    environment:
      - cluster.
      - name=elasticsearch
      - node.name=master-recipes
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=master-recipes
    ports:
      - "9200:9200"
      - "9300:9300"
